// ── Survivor build database ────────────────────────────────────────────────
// core  = grab these first (highest priority)
// add   = layer these on once core is covered
// Equipment and situational picks are noted in the hint
module.exports = [
  {
    name: 'Commando',
    role: 'proc DPS',
    hint: 'Fast-hit scaling: stack proc chains and crit.',
    core: ['syringe', 'glasses', 'atg', 'ukulele', 'shrimp', 'clover'],
    add: ['pred', 'scythe', 'watch', 'icbm'],
    luxury: ['shatterspleen', 'molten', 'gesture', 'tonic', 'crown'],
  },
  {
    name: 'Huntress',
    role: 'mobile clear',
    hint: 'Stay moving; prioritize burst openers + chain clear.',
    core: ['crowbar', 'hoof', 'feather', 'atg', 'ukulele', 'wisp'],
    add: ['glasses', 'polylute', 'clover', 'bandk'],
    luxury: [
      'littledisciple',
      'shatterspleen',
      'gesture',
      'strides',
      'convergence',
    ],
  },
  {
    name: 'Bandit',
    role: 'burst reset',
    hint: 'Backstab burst + execute rhythm; frontload damage.',
    core: ['crowbar', 'rounds', 'backupmag', 'watch', 'bands', 'bandk'],
    add: ['laser', 'justice', 'clover', 'feather'],
    luxury: ['shatterspleen', 'glass', 'convergence', 'crown'],
  },
  {
    name: 'MUL-T',
    role: 'sustained gunner',
    hint: 'Excellent with on-hit and missile scaling.',
    core: ['syringe', 'mocha', 'atg', 'ukulele', 'shrimp', 'icbm'],
    add: ['glasses', 'clover', 'justice', 'tougher'],
    luxury: ['shatterspleen', 'molten', 'gesture', 'tonic', 'knurl'],
  },
  {
    name: 'Engineer',
    role: 'turret scaling',
    hint: 'Turrets inherit items: build for turret uptime + survival.',
    core: ['fungus', 'lysate', 'atg', 'ukulele', 'clover', 'tougher'],
    add: ['icbm', 'nkuhana', 'rack', 'behemoth'],
    luxury: ['knurl', 'nucleus', 'spark', 'convergence', 'stoneflux'],
  },
  {
    name: 'Artificer',
    role: 'ability burst',
    hint: 'Big skill damage windows; bands and cooldown help most.',
    core: ['crowbar', 'bands', 'bandk', 'backupmag', 'ignition', 'alien'],
    add: ['feather', 'purity', 'glass', 'justice'],
    luxury: ['genesisloop', 'molten', 'lightflux', 'gesture', 'convergence'],
  },
  {
    name: 'Mercenary',
    role: 'melee i-frames',
    hint: 'Close-range brawler: mobility, sustain, and burst procs.',
    core: ['crystal', 'syringe', 'glasses', 'scythe', 'feather', 'safer'],
    add: ['watch', 'atg', 'behemoth', 'after'],
    luxury: ['shatterspleen', 'knurl', 'transcendence', 'strides', 'planula'],
  },
  {
    name: 'REX',
    role: 'self-cost control',
    hint: 'Balance self-damage with aggressive sustain and AoE.',
    core: ['weeping', 'scythe', 'ukulele', 'wisp', 'nkuhana', 'rack'],
    add: ['tougher', 'safer', 'clover', 'daggerred'],
    luxury: ['knurl', 'planula', 'miredurn', 'convergence', 'stoneflux'],
  },
  {
    name: 'Loader',
    role: 'one-shot diver',
    hint: 'Single target burst + movement speed = map deletion.',
    core: ['crowbar', 'crystal', 'rounds', 'bands', 'bandk', 'h3ad'],
    add: ['hoof', 'watch', 'after', 'justice'],
    luxury: ['shatterspleen', 'genesisloop', 'molten', 'glass', 'convergence'],
  },
  {
    name: 'Acrid',
    role: 'DoT + clear',
    hint: 'Poison controls bosses; stack clear and utility around it.',
    core: ['gasoline', 'wisp', 'ukulele', 'safer', 'tougher', 'feather'],
    add: ['ignition', 'clover', 'daggerred', 'behemoth'],
    luxury: ['shatterspleen', 'planula', 'miredurn', 'convergence', 'strides'],
  },
  {
    name: 'Captain',
    role: 'all-rounder',
    hint: 'Reliable shotgun and utility; likes proc + drone scaling.',
    core: ['syringe', 'atg', 'ukulele', 'rounds', 'droneparts', 'clover'],
    add: ['icbm', 'justice', 'feather', 'watch'],
    luxury: ['nucleus', 'empathy', 'spark', 'gesture', 'convergence'],
  },
  {
    name: 'Railgunner',
    role: 'precision burst',
    hint: 'Prioritize opener damage and armor shred for boss deletes.',
    core: ['crowbar', 'rounds', 'bands', 'bandk', 'laser', 'justice'],
    add: ['feather', 'watch', 'clover', 'h3ad'],
    luxury: ['shatterspleen', 'molten', 'glass', 'convergence', 'crown'],
  },
  {
    name: 'Void Fiend',
    role: 'form shifter',
    hint: 'Scale fast-hit + survive corruption windows.',
    core: ['syringe', 'shrimp', 'polylute', 'safer', 'lysate', 'clover'],
    add: ['atg', 'watch', 'hook', 'behemoth'],
    luxury: ['genesisloop', 'planula', 'transcendence', 'egocentrism', 'tonic'],
  },
  {
    name: 'Seeker',
    role: 'hybrid skirmisher',
    hint: 'Ability-heavy style: cooldown + mobility + burst windows.',
    core: ['backupmag', 'feather', 'bands', 'bandk', 'alien', 'safer'],
    add: ['watch', 'tougher', 'clover', 'after'],
    luxury: ['planula', 'shatterspleen', 'lightflux', 'strides', 'convergence'],
  },
  {
    name: 'False Son',
    role: 'frontline bruiser',
    hint: 'Tanky pressure with close-mid range damage spikes.',
    core: ['crystal', 'tougher', 'safer', 'syringe', 'justice', 'scythe'],
    add: ['behemoth', 'spark', 'feather', 'watch'],
    luxury: ['knurl', 'planula', 'molten', 'transcendence', 'stoneflux'],
  },
  {
    name: 'CHEF',
    role: 'close-range control',
    hint: 'Excels with ignite/aoe and survivability while brawling.',
    core: ['ignition', 'gasoline', 'wisp', 'crystal', 'tougher', 'feather'],
    add: ['syringe', 'behemoth', 'daggerred', 'clover'],
    luxury: ['molten', 'shatterspleen', 'knurl', 'miredurn', 'convergence'],
  },
  {
    name: 'Operator',
    role: 'ranged sustained',
    hint: 'Lean into rapid-hit proc chains and movement uptime.',
    core: ['syringe', 'glasses', 'atg', 'ukulele', 'shrimp', 'clover'],
    add: ['pred', 'scythe', 'icbm', 'safer'],
    luxury: ['shatterspleen', 'spark', 'gesture', 'tonic', 'crown'],
  },
  {
    name: 'Drifter',
    role: 'utility striker',
    hint: 'Flexible kit: prioritize universal damage + safety.',
    core: ['watch', 'feather', 'atg', 'ukulele', 'tougher', 'safer'],
    add: ['wisp', 'justice', 'clover', 'hook'],
    luxury: ['knurl', 'planula', 'nucleus', 'convergence', 'strides'],
  },
];
