// ── Item database ──────────────────────────────────────────────────────────
// Each entry has: display name, wiki filename (for icon URL), rarity tier, short tag
module.exports = {
  syringe: {
    name: "Soldier's Syringe",
    file: "Soldier's_Syringe.png",
    tier: 'common',
    tag: 'attack speed',
  },
  glasses: {
    name: "Lens-Maker's Glasses",
    file: "Lens-Maker's_Glasses.png",
    tier: 'common',
    tag: 'crit chance',
  },
  hoof: {
    name: "Paul's Goat Hoof",
    file: "Paul's_Goat_Hoof.png",
    tier: 'common',
    tag: 'move speed',
  },
  drink: {
    name: 'Energy Drink',
    file: 'Energy_Drink.png',
    tier: 'common',
    tag: 'sprint speed',
  },
  mocha: {
    name: 'Mocha',
    file: 'Mocha.png',
    tier: 'common',
    tag: 'speed + atk',
  },
  crowbar: {
    name: 'Crowbar',
    file: 'Crowbar.png',
    tier: 'common',
    tag: 'opening burst',
  },
  dagger: {
    name: 'Tri-Tip Dagger',
    file: 'Tri-Tip_Dagger.png',
    tier: 'common',
    tag: 'bleed',
  },
  rounds: {
    name: 'Armor-Piercing Rounds',
    file: 'Armor-Piercing_Rounds.png',
    tier: 'common',
    tag: 'boss damage',
  },
  tougher: {
    name: 'Tougher Times',
    file: 'Tougher_Times.png',
    tier: 'common',
    tag: 'block chance',
  },
  watch: {
    name: 'Delicate Watch',
    file: 'Delicate_Watch.png',
    tier: 'common',
    tag: 'big damage',
  },
  crystal: {
    name: 'Focus Crystal',
    file: 'Focus_Crystal.png',
    tier: 'common',
    tag: 'close-range dmg',
  },
  backupmag: {
    name: 'Backup Magazine',
    file: 'Backup_Magazine.png',
    tier: 'common',
    tag: 'extra charges',
  },
  fungus: {
    name: 'Bustling Fungus',
    file: 'Bustling_Fungus.png',
    tier: 'common',
    tag: 'healing zone',
  },
  gasoline: {
    name: 'Gasoline',
    file: 'Gasoline.png',
    tier: 'common',
    tag: 'clear speed',
  },
  feather: {
    name: 'Hopoo Feather',
    file: 'Hopoo_Feather.png',
    tier: 'uncommon',
    tag: 'extra jump',
  },
  atg: {
    name: 'AtG Missile Mk. 1',
    file: 'AtG_Missile_Mk._1.png',
    tier: 'uncommon',
    tag: 'proc burst',
  },
  ukulele: {
    name: 'Ukulele',
    file: 'Ukulele.png',
    tier: 'uncommon',
    tag: 'chain lightning',
  },
  bands: {
    name: "Runald's Band",
    file: "Runald's_Band.png",
    tier: 'uncommon',
    tag: 'band burst',
  },
  bandk: {
    name: "Kjaro's Band",
    file: "Kjaro's_Band.png",
    tier: 'uncommon',
    tag: 'band burst',
  },
  pred: {
    name: 'Predatory Instincts',
    file: 'Predatory_Instincts.png',
    tier: 'uncommon',
    tag: 'crit atk speed',
  },
  scythe: {
    name: "Harvester's Scythe",
    file: "Harvester's_Scythe.png",
    tier: 'uncommon',
    tag: 'crit heal',
  },
  wisp: {
    name: "Will-o'-the-wisp",
    file: "Will-o'-the-wisp.png",
    tier: 'uncommon',
    tag: 'on-kill aoe',
  },
  ignition: {
    name: 'Ignition Tank',
    file: 'Ignition_Tank.png',
    tier: 'uncommon',
    tag: 'ignite scaling',
  },
  fuel: {
    name: 'Fuel Cell',
    file: 'Fuel_Cell.png',
    tier: 'uncommon',
    tag: 'equipment uses',
  },
  weeping: {
    name: 'Weeping Fungus',
    file: 'Weeping_Fungus.png',
    tier: 'void',
    tag: 'mobile healing',
  },
  shrimp: {
    name: 'Plasma Shrimp',
    file: 'Plasma_Shrimp.png',
    tier: 'void',
    tag: 'shield missiles',
  },
  polylute: {
    name: 'Polylute',
    file: 'Polylute.png',
    tier: 'void',
    tag: 'void chain',
  },
  safer: {
    name: 'Safer Spaces',
    file: 'Safer_Spaces.png',
    tier: 'void',
    tag: 'burst block',
  },
  singularity: {
    name: 'Singularity Band',
    file: 'Singularity_Band.png',
    tier: 'void',
    tag: 'void band',
  },
  lysate: {
    name: 'Lysate Cell',
    file: 'Lysate_Cell.png',
    tier: 'void',
    tag: 'special +1',
  },
  lensvoid: {
    name: "Lost Seer's Lenses",
    file: "Lost_Seer's_Lenses.png",
    tier: 'void',
    tag: 'insta-kill proc',
  },
  clover: {
    name: '57 Leaf Clover',
    file: '57_Leaf_Clover.png',
    tier: 'legendary',
    tag: 'proc consistency',
  },
  justice: {
    name: 'Shattering Justice',
    file: 'Shattering_Justice.png',
    tier: 'legendary',
    tag: 'armor shred',
  },
  behemoth: {
    name: 'Brilliant Behemoth',
    file: 'Brilliant_Behemoth.png',
    tier: 'legendary',
    tag: 'aoe splash',
  },
  hook: {
    name: 'Sentient Meat Hook',
    file: 'Sentient_Meat_Hook.png',
    tier: 'legendary',
    tag: 'extra hits',
  },
  icbm: {
    name: 'Pocket I.C.B.M.',
    file: 'Pocket_I.C.B.M..png',
    tier: 'legendary',
    tag: 'missile amp',
  },
  after: {
    name: 'Hardlight Afterburner',
    file: 'Hardlight_Afterburner.png',
    tier: 'legendary',
    tag: 'utility spam',
  },
  alien: {
    name: 'Alien Head',
    file: 'Alien_Head.png',
    tier: 'legendary',
    tag: 'cdr',
  },
  laser: {
    name: 'Laser Scope',
    file: 'Laser_Scope.png',
    tier: 'legendary',
    tag: 'crit multiplier',
  },
  h3ad: {
    name: 'H3AD-5T v2',
    file: 'H3AD-5T_v2.png',
    tier: 'legendary',
    tag: 'slam burst',
  },
  nkuhana: {
    name: "N'kuhana's Opinion",
    file: "N'kuhana's_Opinion.png",
    tier: 'legendary',
    tag: 'heal to damage',
  },
  rack: {
    name: 'Rejuvenation Rack',
    file: 'Rejuvenation_Rack.png',
    tier: 'legendary',
    tag: 'heal amp',
  },
  daggerred: {
    name: 'Ceremonial Dagger',
    file: 'Ceremonial_Dagger.png',
    tier: 'legendary',
    tag: 'on-kill burst',
  },
  droneparts: {
    name: 'Spare Drone Parts',
    file: 'Spare_Drone_Parts.png',
    tier: 'legendary',
    tag: 'drone power',
  },
  spark: {
    name: 'Charged Perforator',
    file: 'Charged_Perforator.png',
    tier: 'boss',
    tag: 'lightning proc',
  },
  littledisciple: {
    name: 'Little Disciple',
    file: 'Little_Disciple.png',
    tier: 'boss',
    tag: 'sprint dmg',
  },
  shatterspleen: {
    name: 'Shatterspleen',
    file: 'Shatterspleen.png',
    tier: 'boss',
    tag: 'crit bleed explode',
  },
  molten: {
    name: 'Molten Perforator',
    file: 'Molten_Perforator.png',
    tier: 'boss',
    tag: 'fire burst proc',
  },
  knurl: {
    name: 'Titanic Knurl',
    file: 'Titanic_Knurl.png',
    tier: 'boss',
    tag: 'HP + regen',
  },
  genesisloop: {
    name: 'Genesis Loop',
    file: 'Genesis_Loop.png',
    tier: 'boss',
    tag: 'low HP burst',
  },
  planula: {
    name: 'Planula',
    file: 'Planula.png',
    tier: 'boss',
    tag: 'on-hit heal',
  },
  nucleus: {
    name: 'Defense Nucleus',
    file: 'Defense_Nucleus.png',
    tier: 'boss',
    tag: 'drone on kill',
  },
  empathy: {
    name: 'Empathy Cores',
    file: 'Empathy_Cores.png',
    tier: 'boss',
    tag: 'solus drones',
  },
  miredurn: {
    name: 'Mired Urn',
    file: 'Mired_Urn.png',
    tier: 'boss',
    tag: 'siphon nearby',
  },
  gesture: {
    name: 'Gesture of the Drowned',
    file: 'Gesture_of_the_Drowned.png',
    tier: 'lunar',
    tag: 'equip spam',
  },
  glass: {
    name: 'Shaped Glass',
    file: 'Shaped_Glass.png',
    tier: 'lunar',
    tag: 'high risk dmg',
  },
  purity: {
    name: 'Purity',
    file: 'Purity.png',
    tier: 'lunar',
    tag: 'cdr tradeoff',
  },
  tonic: {
    name: 'Spinel Tonic',
    file: 'Spinel_Tonic.png',
    tier: 'lunar',
    tag: 'all stats',
  },
  convergence: {
    name: 'Focused Convergence',
    file: 'Focused_Convergence.png',
    tier: 'lunar',
    tag: 'fast teleporter',
  },
  transcendence: {
    name: 'Transcendence',
    file: 'Transcendence.png',
    tier: 'lunar',
    tag: 'HP to shields',
  },
  strides: {
    name: 'Strides of Heresy',
    file: 'Strides_of_Heresy.png',
    tier: 'lunar',
    tag: 'shadow dash',
  },
  visions: {
    name: 'Visions of Heresy',
    file: 'Visions_of_Heresy.png',
    tier: 'lunar',
    tag: 'homing replace',
  },
  lightflux: {
    name: 'Light Flux Pauldron',
    file: 'Light_Flux_Pauldron.png',
    tier: 'lunar',
    tag: 'CDR less charges',
  },
  stoneflux: {
    name: 'Stone Flux Pauldron',
    file: 'Stone_Flux_Pauldron.png',
    tier: 'lunar',
    tag: 'HP up speed down',
  },
  egocentrism: {
    name: 'Egocentrism',
    file: 'Egocentrism.png',
    tier: 'lunar',
    tag: 'scaling orbs',
  },
  crown: {
    name: 'Brittle Crown',
    file: 'Brittle_Crown.png',
    tier: 'lunar',
    tag: 'gold on hit',
  },

  // ── New items (expansion for variants / Eclipse / Prismatic) ─────────────
  infusion: {
    name: 'Infusion',
    file: 'Infusion.png',
    tier: 'common',
    tag: 'permanent HP',
  },
  medkit: {
    name: 'Medkit',
    file: 'Medkit.png',
    tier: 'common',
    tag: 'delayed heal',
  },
  topazbrooch: {
    name: 'Topaz Brooch',
    file: 'Topaz_Brooch.png',
    tier: 'common',
    tag: 'on-kill barrier',
  },
  stun: {
    name: 'Stun Grenade',
    file: 'Stun_Grenade.png',
    tier: 'common',
    tag: 'on-hit stun',
  },
  repulsion: {
    name: 'Repulsion Armor Plate',
    file: 'Repulsion_Armor_Plate.png',
    tier: 'common',
    tag: 'flat DR',
  },
  quail: {
    name: 'Wax Quail',
    file: 'Wax_Quail.png',
    tier: 'uncommon',
    tag: 'jump boost',
  },
  buckler: {
    name: 'Rose Buckler',
    file: 'Rose_Buckler.png',
    tier: 'uncommon',
    tag: 'sprint armor',
  },
  stealthkit: {
    name: 'Old War Stealthkit',
    file: 'Old_War_Stealthkit.png',
    tier: 'uncommon',
    tag: 'low HP escape',
  },
  berzerker: {
    name: "Berzerker's Pauldron",
    file: "Berzerker's_Pauldron.png",
    tier: 'uncommon',
    tag: 'multi-kill frenzy',
  },
  warhorn: {
    name: 'War Horn',
    file: 'War_Horn.png',
    tier: 'uncommon',
    tag: 'equip atk speed',
  },
  squid: {
    name: 'Squid Polyp',
    file: 'Squid_Polyp.png',
    tier: 'uncommon',
    tag: 'turret on activate',
  },
  aegis: {
    name: 'Aegis',
    file: 'Aegis.png',
    tier: 'legendary',
    tag: 'overheal barrier',
  },
  raincoat: {
    name: "Ben's Raincoat",
    file: "Ben's_Raincoat.png",
    tier: 'legendary',
    tag: 'debuff immunity',
  },
  scorpion: {
    name: 'Symbiotic Scorpion',
    file: 'Symbiotic_Scorpion.png',
    tier: 'legendary',
    tag: 'perm armor shred',
  },
  tesla: {
    name: 'Unstable Tesla Coil',
    file: 'Unstable_Tesla_Coil.png',
    tier: 'legendary',
    tag: 'passive aoe',
  },
  needletick: {
    name: 'Needletick',
    file: 'Needletick.png',
    tier: 'void',
    tag: 'collapse proc',
  },
  voidsent: {
    name: 'Voidsent Flame',
    file: 'Voidsent_Flame.png',
    tier: 'void',
    tag: 'void burst aoe',
  },
  chaos: {
    name: 'Bottled Chaos',
    file: 'Bottled_Chaos.png',
    tier: 'void',
    tag: 'random equip',
  },
};
